info:
  component: Config Samples
endpoints:
  restart:
    enabled: true
logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG
    org.springframework.cloud: DEBUG
spring:
  application:
    name: spring-cloud-eureka-feign-client
server:
  port: 8080

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
#    default:
    "GreetingClient#greeting":
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
#    "GreetingClient#greeting(String,String)":
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 20000
#Ribbon 超时时间设置
#ribbon:
#  ConnectTimeout: 50000
 # ReadTimeout:  30000
 
# try hystrix.command.<hystrixcommandkey>.execution.isolation.thread.timeoutInMilliseconds


#The hystrixcommandkey takes the format of FeignClassName#methodSignature. See #1864.